# Generated by Django 6.0.5 on 2026-07-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['checked_in'], name='participant_checked_279020_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['banned'], name='participant_banned_8eb349_idx'),
        ),
    ]
