# Generated by Django 6.0.5 on 2026-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displaydevice",
            name="location",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
