# Generated by Django 6.0.5 on 2026-07-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_displaydevice_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="display_mode",
            field=models.CharField(
                choices=[("chat", "Chat"), ("crawling", "Crawling")],
                default="chat",
                max_length=16,
            ),
        ),
    ]
