# Generated by Django 6.0.5 on 2026-07-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_settings_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='event_api_jsonq_filter',
            field=models.TextField(blank=True, default='', help_text='jq filter applied to the event API response.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='event_api_url',
            field=models.URLField(blank=True),
        ),
    ]
