# Generated by Django 6.0.5 on 2026-07-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_settings_event_api_jsonq_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
