# Generated by Django 6.0.5 on 2026-07-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_synclock'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='spam_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
