# Generated by Django 6.0.5 on 2026-06-08 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("participants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                ("allow_messages", models.BooleanField(default=True)),
                (
                    "display_mode",
                    models.CharField(
                        blank=True,
                        help_text="chat or crawling. null = use global setting",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "scroll_speed_px",
                    models.IntegerField(
                        blank=True,
                        help_text="Pixels per frame in crawling mode. null = use global setting",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=4096)),
                ("raw_content", models.TextField(blank=True, null=True)),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "Text"),
                            ("photo", "Photo"),
                            ("gif", "GIF"),
                            ("sticker", "Sticker"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("media_url", models.URLField(blank=True, null=True)),
                (
                    "sticker_emoji",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("spam_score", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("displayed", "Displayed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_event", "No active event"),
                            ("unknown", "Unknown participant"),
                            ("not_checkedin", "Not checked in"),
                            ("banned", "Banned"),
                            ("rate_limit", "Rate limited"),
                            ("offline", "Bot offline"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("displayed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="streaming.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="streaming_m_status_25f962_idx",
                    ),
                    models.Index(
                        fields=["participant", "created_at"],
                        name="streaming_m_partici_d138ea_idx",
                    ),
                ],
            },
        ),
    ]
