# Generated by Django 6.0.5 on 2026-07-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_event_display_mode_alter_message_media_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='streaming_e_is_acti_20e2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at', 'ends_at'], name='streaming_e_starts__667433_idx'),
        ),
    ]
