# Generated by Django 6.0.5 on 2026-07-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_displaydevice_location"),
        ("streaming", "0004_mediaasset_message_media_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("killswitch", "Killswitch"),
                            ("pause", "Pause"),
                            ("resume", "Resume"),
                            ("clear", "Clear"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="mediaasset",
            new_name="streaming_m_media_t_43ea51_idx",
            old_name="streaming_media_mt_idx",
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="animated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="duration_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="format",
            field=models.CharField(default="webp", editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="frame_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="has_alpha",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="sha256",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="displayevent",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.displaydevice",
            ),
        ),
        migrations.AddIndex(
            model_name="displayevent",
            index=models.Index(
                fields=["device", "occurred_at"], name="streaming_d_device__72af4f_idx"
            ),
        ),
    ]
