# Generated by Django 6.0.5 on 2026-07-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streaming", "0005_displayevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="display_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Global setting"),
                    ("chat", "Chat"),
                    ("crawling", "Crawling"),
                ],
                default="",
                help_text="chat or crawling. null = use global setting",
                max_length=16,
            ),
        ),
    ]
