# Generated by Django 6.0.5 on 2026-07-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_alter_event_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
