# Generated by Django 6.0.5 on 2026-07-20 07:47

from django.db import migrations, models


def keep_one_active_event(apps, schema_editor):  # noqa: ARG001
    Event = apps.get_model("streaming", "Event")
    active_ids = list(
        Event.objects.filter(is_active=True)
        .order_by("-starts_at", "-id")
        .values_list("id", flat=True)
    )
    if len(active_ids) > 1:
        Event.objects.filter(id__in=active_ids[1:]).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_event_external_id'),
    ]

    operations = [
        migrations.RunPython(keep_one_active_event, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='streaming_single_active_event'),
        ),
    ]
