# Generated by Django 6.0.5 on 2026-07-20 09:22

from django.db import migrations, models


def migrate_displayed_to_approved(apps, schema_editor):
    Message = apps.get_model("streaming", "Message")
    Message.objects.filter(status="displayed").update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0008_event_streaming_single_active_event"),
    ]

    operations = [
        migrations.RunPython(migrate_displayed_to_approved, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
