# Generated by Django 6.0.5 on 2026-07-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_normalize_spam_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('no_event', 'No active event'), ('unknown', 'Unknown participant'), ('not_checkedin', 'Not checked in'), ('banned', 'Banned'), ('rate_limit', 'Rate limited'), ('offline', 'Bot offline'), ('spam', 'Spam'), ('inappropriate', 'Unpassend'), ('duplicate', 'Duplikat'), ('nsfw', 'NSFW'), ('moderator_other', 'Sonstiger Moderationsgrund')], default='', max_length=32),
        ),
    ]
