# Generated by Django 5.2.12 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("streaming", "0012_alter_message_rejection_reason")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_event", "No active event"),
                    ("messages_disabled", "Messages disabled for active event"),
                    ("maintenance", "Bot maintenance"),
                    ("unknown", "Unknown participant"),
                    ("not_checkedin", "Not checked in"),
                    ("banned", "Banned"),
                    ("rate_limit", "Rate limited"),
                    ("offline", "Bot offline"),
                    ("spam", "Spam"),
                    ("inappropriate", "Unpassend"),
                    ("duplicate", "Duplikat"),
                    ("nsfw", "NSFW"),
                    ("moderator_other", "Sonstiger Moderationsgrund"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
