name: Django Tests
on: [ push, pull_request ]

jobs:
  django-tests:
    runs-on: ubuntu-latest
    container: "python:3.14"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: dev_user
          POSTGRES_PASSWORD: dev_pass
          POSTGRES_DB: dev_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Install pipx
        run: python3 -m pip install pipx && pipx ensurepath
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: main
      - name: Install dependencies
        run: /github/home/.local/bin/poetry install --with dev
      - name: Copy dev .env
        run: cp -f dev/.env .env
      - name: Run django migrations
        run: /github/home/.local/bin/poetry run paws_on_stream_web/manage.py migrate --no-input
      - name: Run django tests
        run: >-
          /github/home/.local/bin/poetry run coverage run
          --source=paws_on_stream_web
          paws_on_stream_web/manage.py test core participants streaming dashboard
      - name: Enforce coverage
        run: /github/home/.local/bin/poetry run coverage report --fail-under=80
